name: Go Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "work" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go version (1.23.2)
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Test
      run: go test -v ./...